version: '3.8'

services:
  symfony_good_practices_nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony-good-practices
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - symfony_good_practices_app
      - symfony_good_practices_database

  symfony_good_practices_app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony-good-practices
      - ~/.gitconfig:/etc/gitconfig
    container_name: symfony_good_practices_app
    links:
      - symfony_good_practices_database

  symfony_good_practices_database:
    image: mysql:8.0
    container_name: symfony_good_practices_database
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - database_volume:/var/lib/mysql

  symfony_good_practices_swagger:
    image: swaggerapi/swagger-ui:v3.52.0
    container_name: symfony_good_practices_swagger
    ports:
      - '9001:8080'
    volumes:
      - ./public:/swagger
    environment:
      - SWAGGER_JSON=/swagger/universe.yaml

  mailer:
    image: schickling/mailcatcher
    ports: ['1025', '1080']

volumes:
  database_volume: