openapi: 3.0.0
info:
  title: 'Universe Web Api'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:9000'
    description: Development
paths:
  /download-excel-planets-list:
    get:
      tags:
        - planet
      description: 'Download excel planets list'
      operationId: c5b6dd177d26caf9f6ff674cccf286ea
      responses:
        '200':
          description: 'Binary file'
  /download-word-planets-list:
    get:
      tags:
        - planet
      description: 'Download word planets list'
      operationId: 79f8981e10cef38fd4b1b115802c7fae
      responses:
        '200':
          description: 'Binary file'
  /planets:
    get:
      tags:
        - planet
      description: 'List planets'
      operationId: dad0dedb46c818af8a1a1ab3590f5675
      parameters:
        -
          name: name
          in: query
          description: 'Planet name to filter'
          required: true
          schema:
            type: string
        -
          name: offset
          in: query
          description: 'Offset to paginate results'
          schema:
            type: integer
        -
          name: limit
          in: query
          description: 'Limit to paginate results'
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                properties:
                  total: { type: integer }
                  offset: { type: integer }
                  limit: { type: integer }
                  results: { type: array, items: { properties: { name: { type: string } }, type: object } }
                type: object
  '/register-user/{uuid}':
    post:
      tags:
        - user
      description: 'Register user'
      operationId: ae521d0d1ec2a3bbf493e1a4fa9d5899
      parameters:
        -
          name: email
          in: query
          description: 'User email'
          required: true
          schema:
            type: string
        -
          name: password
          in: query
          description: 'User password'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: 'Bad Request'
  '/user/{uuid}/update-profile':
    post:
      tags:
        - user
      description: 'Update profile user'
      operationId: f6addf7958e00d546074d33fc07e1b38
      parameters:
        -
          name: street
          in: query
          description: 'User street'
          required: false
          schema:
            type: string
        -
          name: number
          in: query
          description: 'User number'
          required: false
          schema:
            type: string
        -
          name: city
          in: query
          description: 'User city'
          required: false
          schema:
            type: string
        -
          name: country
          in: query
          description: 'User country'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: 'User not found'
tags:
  -
    name: planet
    description: planet
  -
    name: user
    description: user
